In [ ]:
import numpy as np
#teste01

In [2]:
print("--- Exercício 1 ---")

arr1 = np.arange(1, 11)
print(f"Array original: {arr1}")


arr1[5:9] = 0
print(f"Array modificado: {arr1}\n")

--- Exercício 1 ---
Array original: [ 1  2  3  4  5  6  7  8  9 10]
Array modificado: [ 1  2  3  4  5  0  0  0  0 10]



In [3]:
print("--- Exercício 2 ---")

arr2 = np.arange(1, 7).reshape(3, 2)
print(f"Matriz:\n{arr2}")

print(f"Shape da matriz: {arr2.shape}")

print(f"2ª linha: {arr2[1]}\n")

--- Exercício 2 ---
Matriz:
[[1 2]
 [3 4]
 [5 6]]
Shape da matriz: (3, 2)
2ª linha: [3 4]



In [4]:
print("--- Exercício 3 ---")

arr3 = np.array([[10, 20],
                 [30, 40],
                 [50, 60]])
print(f"Matriz:\n{arr3}")

print(f"2ª coluna: {arr3[:, 1]}\n")

--- Exercício 3 ---
Matriz:
[[10 20]
 [30 40]
 [50 60]]
2ª coluna: [20 40 60]



In [5]:
print("--- Exercício 4 ---")

arr4 = np.arange(1, 21).reshape(4, 5)
print(f"Matriz:\n{arr4}")

print(f"3ª linha: {arr4[2]}\n")

--- Exercício 4 ---
Matriz:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
3ª linha: [11 12 13 14 15]



In [6]:
print("--- Exercício 5 ---")

arr5 = np.arange(101, 121).reshape(4, 5)
print(f"Matriz:\n{arr5}")

print("Elementos (linhas 1 e 2 | colunas 2 e 3):")
print(f"{arr5[0:2, 1:3]}\n")

--- Exercício 5 ---
Matriz:
[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]]
Elementos (linhas 1 e 2 | colunas 2 e 3):
[[102 103]
 [107 108]]



In [7]:
print("--- Exercício 6 ---")

arr6 = np.random.randint(1, 100, size=(4, 5))
print(f"Matriz:\n{arr6}")

print("Elementos (linhas 2 e 3 | colunas 1 a 3):")
print(f"{arr6[1:3, 0:3]}\n")

--- Exercício 6 ---
Matriz:
[[ 6 34  5 65 39]
 [12 28 98 46 98]
 [46 47 87 11  5]
 [64 31 18  1 16]]
Elementos (linhas 2 e 3 | colunas 1 a 3):
[[12 28 98]
 [46 47 87]]

